project:
  type: website
  output-dir: docs

website:
  description: "TODO: A blog built with Quarto"
  site-url: https://daniilgaltsev.github.io # you must change this appropriately for RSS feeds to work properly
  title: "Dan's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/daniilgaltsev
format:
  html:
    theme:
      light: lumen
      dark: darkly
    css: styles.css

